language: generic
addons:
    apt:
        packages:
            - pandoc
            - pandoc-citeproc
            - texlive-full
script:
        - pandoc --filter pandoc-citeproc --bibliography=winnowing.bib winnowing.md -o winnowing.pdf
        - mkdir _build
        - mv winnowing.pdf _build
os:
        - linux