language: generic
addons:
    apt:
        packages:
            - pandoc
            - texlive-humanities
script:
        - pandoc --filter pandoc-citeproc --bibliography=winnowing.bib winnowing.md -o winnowing.pdf
os:
        - linux